Restaurants/Models/Cuisine.cs
using System.Collections.Generic;

namespace Restaurants.Models
{
  public class Cuisine
  {
    public Cuisine()
    {
      this.Restaurants = new HashSet<Restaurant>();
    }

    public string Name {get; set;}
    public int CuisineId {get; set;}

    public virtual ICollection<Restaurant> Restaurants { get; set; }
  }
  
}

Restaurants/Models/Restaurant.cs
namespace Restaurants.Models
{
  public class Restaurant
  {

    public string Name {get; set;}
    public string Dishes {get; set;}
    public string Phone {get; set;}
    // [Display("Takes Reservations")]
    public bool Reservations {get; set;}
    public int RestaurantId {get; set;}
    public int CuisineId {get; set;}

    public virtual Cuisine Cuisine { get; set; }
  }
  
}

Restaurants/Models/RestaurantsContext.cs
using Microsoft.EntityFrameworkCore;

namespace Restaurants.Models
{
  public class RestaurantsContext : DbContext
  {
    public DbSet<Cuisine> Cuisines { get; set; } 
    public DbSet<Restaurant> Restaurants { get; set; } 

    public RestaurantsContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Restaurants/Controllers/CuisinesController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Restaurants.Controllers
{
  public class CuisinesController : Controller
  {
    private readonly RestaurantsContext _db;

    public CuisinesController(RestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index() { 
      //list
      List<Cuisine> model = _db.Cuisines.ToList();
      return View(model); 
    }

    public ActionResult Create() 
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Cuisine cuisine) 
    {
      _db.Cuisines.Add(cuisine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id,bool filtered)
    {
      Cuisine chosenCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);

      ViewBag.Filtered = filtered;
      
      if(filtered){
        List<Restaurant> associatedRestaurants = _db.Restaurants.ToList().Where(restaurant => restaurant.CuisineId == id).ToList();

        ViewBag.AssociatedRestaurants = associatedRestaurants; 
      }
      
    
      
      return View(chosenCuisine);
    }

    // [HttpPost, ActionName("Details")]
    // public ActionResult DetailsFilter(int id)
    // {
    //   Cuisine chosenCuisine = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      
    //   chosenCuisine.Showing = true;
    //   RedirectToAction("Details");
    // }

    //post route from a form in details, -have another property - boolean? ShowingAllRestauraunts - if true, set to true, then if true in 

    public ActionResult Edit(int id)
    {
      Cuisine cuisineToEdit = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(cuisineToEdit);
    }

    [HttpPost]
    public ActionResult Edit(Cuisine cuisine)
    {
      _db.Entry(cuisine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Cuisine cuisineToDelete = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      return View(cuisineToDelete);
    }
    
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Cuisine cuisineToDelete = _db.Cuisines.FirstOrDefault(cuisine => cuisine.CuisineId == id);
      _db.Cuisines.Remove(cuisineToDelete);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Restaurants/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Restaurants.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index() { 
      return View(); 
    }
  }
}

Restaurants/Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using Restaurants.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Restaurants.Controllers
{
  public class RestaurantsController : Controller
  {
    private readonly RestaurantsContext _db;

    public RestaurantsController(RestaurantsContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Restaurant> model = _db.Restaurants.Include(restaurant => restaurant.Cuisine).ToList();
      return View(model);
    }
    
    public ActionResult Create()
    {
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View();
    }
    
    [HttpPost]
    public ActionResult Create(Restaurant restaurant)
    {
      _db.Restaurants.Add(restaurant);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Restaurant chosenRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(chosenRestaurant);
    }

    public ActionResult Edit(int id)
    {
      Restaurant restaurantToEdit = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      ViewBag.CuisineId = new SelectList(_db.Cuisines, "CuisineId", "Name");
      return View(restaurantToEdit);
    }

    [HttpPost]
    public ActionResult Edit(Restaurant restaurant)
    {
      _db.Entry(restaurant).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    
    public ActionResult Delete(int id)
    {
      Restaurant restaurantToDelete = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      return View(restaurantToDelete);
    }
    
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Restaurant restaurantToDelete = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
      _db.Restaurants.Remove(restaurantToDelete);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Restaurants/Views/Cuisines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Cuisine

<h3>Add a new cuisine type:</h3>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add" />
}

<p>@Html.ActionLink("Show all cuisines","Index")</p>

Restaurants/Views/Cuisines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Cuisine

<h2>Are you sure you want to delete this cuisine?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to cuisines", "Index")

Restaurants/Views/Cuisines/Details.cshtml
@using Restaurants.Models
@using System
@using System.Collections.Generic

@{
  Layout = "_Layout";
}

@model Restaurants.Models.Cuisine

<h2>View cuisine details</h2>
<hr />
<h3>@Html.DisplayFor(model => model.Name)</h3> 

@if(ViewBag.Filtered)
{
  <ul>
    @foreach(Restaurant restaurant in @ViewBag.AssociatedRestaurants)
    {
      <li>@Html.ActionLink($"{restaurant.Name}", "Details", "Restaurants", new { id = restaurant.RestaurantId})</li>
    }
  </ul>
}
else
{
  <p>@Html.ActionLink($"Show restaurants serving this cuisine", "Details", new { id = Model.CuisineId, filtered = true })</p>
}

<p>@Html.ActionLink("Edit Cuisine", "Edit", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Delete Cuisine", "Delete", new { id = Model.CuisineId })</p>
<p>@Html.ActionLink("Back to all cuisines", "Index")</p>

Restaurants/Views/Cuisines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Cuisine

<h2>Edit</h2>

<h4>Edit this cuisine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.CuisineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to cuisines", "Index")</p>

Restaurants/Views/Cuisines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Restaurants.Models

<h1>Types of cuisines</h1>

@if (Model.Count == 0)
{
  <p>No cuisine types have been added yet.</p>
}

<ul>
@foreach (Cuisine cuisine in Model)
{
  <li>@Html.ActionLink($"{cuisine.Name}", "Details", new { id = cuisine.CuisineId, filtered = false })</li>
}
</ul>

<p>@Html.ActionLink("Add a cuisine type", "Create", "Cuisines")</p>
<p>@Html.ActionLink("Return to home", "Index", "Home")</p>

Restaurants/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
  <h1>Track your favorite restaurants</h1>

  @Html.ActionLink("View cuisines", "Index", "Cuisines")
  @Html.ActionLink("View restaurants", "Index", "Restaurants")

Restaurants/Views/Restaurants/Create.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h3>Add a new restaurant</h3>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Dishes)
  @Html.TextBoxFor(model => model.Dishes)

  @Html.LabelFor(model => model.Phone)
  @Html.TextBoxFor(model => model.Phone)

  @Html.LabelFor(model => model.Reservations)
  @Html.CheckBoxFor(model => model.Reservations)

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Add new restaurant" />
}

<p>@Html.ActionLink("Show all restaurants", "Index")</p>

Restaurants/Views/Restaurants/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>Are you sure you want to delete this restaurant?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

@Html.ActionLink("Back to restaurants", "Index")

Restaurants/Views/Restaurants/Details.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>Restaurant Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Dishes): @Html.DisplayFor(model => model.Dishes)<h3>
<h3>@Html.DisplayNameFor(model => model.Phone): @Html.DisplayFor(model => model.Phone)<h3>
<h3>@Html.DisplayNameFor(model => model.Reservations): 
  @if(Model.Reservations)
  {
    <span>Yes</span>
  }
  else
  {
    <span>No</span>
  }
  @* @Html.DisplayFor(model => model.Reservations) *@
  
  <h3>
<p>@Html.ActionLink("Edit Restaurant", "Edit", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Delete Restaurant", "Delete", new { id = Model.RestaurantId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

Restaurants/Views/Restaurants/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Restaurants.Models.Restaurant

<h2>Edit</h2>

<h4>Edit this restaurant: @Html.DisplayFor(model => model.Name) Id: @Html.DisplayFor(model => model.CuisineId)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.RestaurantId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.Dishes)
  @Html.EditorFor(model => model.Dishes)

  @Html.LabelFor(model => model.Phone)
  @Html.EditorFor(model => model.Phone)

  @Html.LabelFor(model => model.Reservations)
  @Html.CheckBoxFor(model => model.Reservations)

  @Html.LabelFor(model => model.Cuisine)
  @Html.DropDownList("CuisineId")

  <input type="submit" value="Save changes">
}

<p>@Html.ActionLink("Back to restaurants", "Index")</p>

Restaurants/Views/Restaurants/Index.cshtml
@{
  Layout = "_Layout";
}

@using Restaurants.Models;
@model List<Restaurants.Models.Restaurant>;

<h2>Restaurants:</h2>

@if (@Model.Count == 0)
{
  <h3>No restaurants have been added to this cuisine type yet.</h3>
}

<ul>
@foreach (Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId}) | @restaurant.Cuisine.Name</li>
}
</ul>

<p>@Html.ActionLink("Add new restaurant", "Create")</p>
<p>@Html.ActionLink("Return to home", "Index", "Home")</p>

Restaurants/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
  </body>
</html>